# Generated by Django 4.0.4 on 2022-05-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_valorantaccount_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorantaccount',
            name='riot_id',
            field=models.CharField(blank=True, help_text='Valorant In Game Name (riot ID)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='valorantaccount',
            name='tagline',
            field=models.CharField(blank=True, help_text='Valorant In Game Tag', max_length=100, null=True),
        ),
    ]
