# Generated by Django 4.0.4 on 2022-05-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_valorantaccount_riot_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorantaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
