# Generated by Django 4.0.4 on 2022-06-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_valorantaccount_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorantaccount',
            name='username',
            field=models.CharField(help_text='Valorant Account Username', max_length=100, unique=True),
        ),
    ]
